import mainPage from './mainpage';
import register from './register';
import login from './login';
import business from './business';
import calendar from './calendartemp';
import homepage from './homepage';
import forgotPassword from './forgotPassword';
import recentBusinesses from './recentBusinesses';
import turns from './myAppointments';
import profile from './myProfile';
import configuration from './configuration';
import favorites from './favorites';
import authenticate from './authenticatePage';

export const HomePage = homepage;
export const Business = business;
export const MainPage = mainPage;
export const Register = register;
export const Login = login;
export const CalendarTemp = calendar;
export const Forgot = forgotPassword;
export const Recent = recentBusinesses;
export const Turns = turns;
export const Profile = profile;
export const Config = configuration;
export const Favs = favorites;
export const Auth = authenticate;
