import business from './business';
import calendar from './calendar-template';
import homepage from './homepage';
import forgotPassword from './forgot-password';
import recentBusinesses from './recent-businesses';
import turns from './my-appointments';
import profile from './my-profile';
import configuration from './configuration';
import favorites from './favorites';
import authenticate from './authenticate-page';

export const HomePage = homepage;
export const Business = business;
export const CalendarTemp = calendar;
export const Forgot = forgotPassword;
export const Recent = recentBusinesses;
export const Turns = turns;
export const Profile = profile;
export const Config = configuration;
export const Favs = favorites;
export const Auth = authenticate;
